#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

if (isset($argv[1]) && $argv[1] == "test") {
    define("TEST_MODE",1);
} else {
    define("TEST_MODE",0);
}
$app = require_once __DIR__ . '/bootstrap/app.php';
